# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190416_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnav',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '删除')], default=1, verbose_name='状态'),
        ),
    ]
