# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_topnav_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topnav',
            old_name='_url',
            new_name='url',
        ),
    ]
