# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-21 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190421_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', verbose_name='渲染后的内容'),
        ),
    ]
