# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='阅读量'),
        ),
        migrations.AddField(
            model_name='post',
            name='uv',
            field=models.IntegerField(default=0, verbose_name='日用户量'),
        ),
    ]
