# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-28 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190428_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=False, verbose_name='支持Markdown格式'),
        ),
    ]
