# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.CharField(max_length=2000, null=True, verbose_name='评论目标'),
        ),
    ]
